



$(function(){"use strict";$('[data-toggle="control-sidebar"]').controlSidebar(),$('[data-toggle="push-menu"]').pushMenu();var e=$('[data-toggle="push-menu"]').data("lte.pushmenu"),a=$('[data-toggle="control-sidebar"]').data("lte.controlsidebar"),t=$("body").data("lte.layout"),i=["theme-primary","theme-success","theme-info","theme-secondary","theme-warning","theme-danger"];function l(i){$("body").toggleClass(i),$("body").hasClass("fixed")&&"fixed"==i&&(e.expandOnHover(),t.activate()),a.fix()}function s(e){var a,t;return $.each(i,function(e){$("body").removeClass(i[e])}),$("body").addClass(e),a="theme",t=e,"undefined"!=typeof Storage?localStorage.setItem(a,t):window.alert("Please use a modern browser to properly view this template!"),!1}var d=$("<div />",{id:"control-sidebar-theme-demo-options-tab",class:"tab-pane active"}),n=$("<li />",{class:"nav-item"}).html("<a href='#control-sidebar-theme-demo-options-tab' class='active' data-bs-toggle='tab' title='Setting'><i class=\"mdi mdi-settings\"></i></a>");$('[href="#control-sidebar-home-tab"]').parent().before(n);var o=$("<div />");o.append('<h4 class="control-sidebar-heading p-0"></h4><div class="flexbox mb-10 pb-10 bb-1 light-on-off"><label for="toggle_left_sidebar_skin" class="control-sidebar-subheading">Dark or Light Skin</label><label class="switch"><input type="checkbox" data-mainsidebarskin="toggle" id="toggle_left_sidebar_skin"><span class="switch-on fs-30"><i class="mdi mdi-lightbulb-on"></i></span><span class="switch-off fs-30"><i class="mdi mdi-lightbulb"></i></span></label></div>'),o.append('<h4 class="control-sidebar-heading p-0"></h4><div class="flexbox mb-10 pb-10 bb-1"><label for="rtl" class="control-sidebar-subheading">Turn RTL/LTR</label><label class="switch switch-border switch-danger"><input type="checkbox" data-layout="rtl" id="rtl"><span class="switch-indicator"></span><span class="switch-description"></span></label></div>');var r=$("<ul />",{class:"list-inline clearfix theme-switch"}),c=$("<li />",{style:"padding: 5px;line-height: 25px;"}).append('<a href="javascript:void(0)" data-theme="theme-primary" style="display: inline-block;vertical-align: middle;" class="clearfix active bg-primary rounded w-80 h-80" title="Theme Primary"></a>');r.append(c);var h=$("<li />",{style:"padding: 5px;line-height: 25px;"}).append('<a href="javascript:void(0)" data-theme="theme-success" style="display: inline-block;vertical-align: middle;" class="clearfix bg-success rounded w-80 h-80" title="Theme Success"></a>');r.append(h);var p=$("<li />",{style:"padding: 5px;line-height: 25px;"}).append('<a href="javascript:void(0)" data-theme="theme-info" style="display: inline-block;vertical-align: middle;" class="clearfix bg-info rounded w-80 h-80" title="Theme Info"></a>');r.append(p);var b=$("<li />",{style:"padding: 5px;line-height: 25px;"}).append('<a href="javascript:void(0)" data-theme="theme-secondary" style="display: inline-block;vertical-align: middle;" class="clearfix bg-secondary rounded w-80 h-80" title="Theme Secondary"></a>');r.append(b);var g=$("<li />",{style:"padding: 5px;line-height: 25px;"}).append('<a href="javascript:void(0)" data-theme="theme-warning" style="display: inline-block;vertical-align: middle;" class="clearfix bg-warning rounded w-80 h-80" title="Theme Warning"></a>');r.append(g);var m,u=$("<li />",{style:"padding: 5px;line-height: 25px;"}).append('<a href="javascript:void(0)" data-theme="theme-danger" style="display: inline-block;vertical-align: middle;" class="clearfix bg-danger rounded w-80 h-80" title="Theme Danger"></a>');r.append(u),o.append('<h4 class="control-sidebar-heading">Skin Colors</h4>'),o.append(r),d.append(o),$("#control-sidebar-home-tab").after(d),(m=function(e){if("undefined"!=typeof Storage)return localStorage.getItem(e);window.alert("Please use a modern browser to properly view this template!")}("theme"))&&$.inArray(m,i)&&s(m),$("[data-theme]").on("click",function(e){$(this).hasClass("knob")||(e.preventDefault(),s($(this).data("theme")))}),$("[data-layout]").on("click",function(){l($(this).data("layout"))}),$("[data-controlsidebar]").on("click",function(){l($(this).data("controlsidebar"));var e=!a.options.slide;a.options.slide=e,e||$(".control-sidebar").removeClass("control-sidebar-open")}),$('[data-enable="expandOnHover"]').on("click",function(){$(this).attr("disabled",!0),e.expandOnHover(),$("body").hasClass("sidebar-collapse")||$('[data-layout="sidebar-collapse"]').click()}),$('[data-enable="rtl"]').on("click",function(){$(this).attr("disabled",!0),e.expandOnHover(),$("body").hasClass("rtl")||$('[data-layout="rtl"]').click()}),$('[data-mainsidebarskin="toggle"]').on("click",function(){var e=$("body");e.hasClass("dark-skin")?(e.removeClass("dark-skin"),e.addClass("light-skin")):(e.removeClass("light-skin"),e.addClass("dark-skin"))}),$("body").hasClass("fixed")&&$('[data-layout="fixed"]').attr("checked","checked"),$("body").hasClass("layout-boxed")&&$('[data-layout="layout-boxed"]').attr("checked","checked"),$("body").hasClass("sidebar-collapse")&&$('[data-layout="sidebar-collapse"]').attr("checked","checked"),$("body").hasClass("rtl")&&$('[data-layout="rtl"]').attr("checked","checked"),$('[data-toggle="tooltip"]').tooltip()}),$(function(){"use strict";$(".theme-switch li a").click(function(){$(".theme-switch li a").removeClass("active").addClass("inactive"),$(this).toggleClass("active inactive")})});











$(function(){$('[data-mainsidebarskin="toggle"]').on("click",function(){$.ajax({type:'GET',url:'${pageContext.request.contextPath}/Notification/change_Skin',data:""});})})












  

